/****
****
**** THIS CODE IS GENERATED BY jetbrains.buildServer.nuget.tests.server.entity.EntityGenerator$EntityInterfaceGenerator
**** DO NOT CHANGE!
**** Generated with class jetbrains.buildServer.nuget.tests.server.entity.EntityGenerator
**** 
*****/
package jetbrains.buildServer.nuget.server.feed.server.javaFeed.entity;

import java.util.*;
import java.lang.*;
import org.odata4j.core.*;
import org.odata4j.internal.*;
import org.joda.time.*;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public interface PackageEntityV2  { 

  @NotNull
  java.lang.String getId();

  @NotNull
  java.lang.String getVersion();

  @NotNull
  java.lang.String getAuthors();

  @NotNull
  java.lang.String getCopyright();

  @NotNull
  org.joda.time.LocalDateTime getCreated();

  @NotNull
  java.lang.String getDependencies();

  @NotNull
  java.lang.String getDescription();

  @NotNull
  java.lang.Integer getDownloadCount();

  @NotNull
  java.lang.String getGalleryDetailsUrl();

  @NotNull
  java.lang.String getIconUrl();

  @NotNull
  java.lang.Boolean getIsLatestVersion();

  @NotNull
  java.lang.Boolean getIsAbsoluteLatestVersion();

  @NotNull
  java.lang.Boolean getIsPrerelease();

  @NotNull
  java.lang.String getLanguage();

  @NotNull
  org.joda.time.LocalDateTime getLastUpdated();

  @NotNull
  org.joda.time.LocalDateTime getPublished();

  @NotNull
  java.lang.String getLicenseUrl();

  @NotNull
  java.lang.String getPackageHash();

  @NotNull
  java.lang.String getPackageHashAlgorithm();

  @NotNull
  java.lang.Long getPackageSize();

  @NotNull
  java.lang.String getProjectUrl();

  @NotNull
  java.lang.String getReportAbuseUrl();

  @NotNull
  java.lang.String getReleaseNotes();

  @NotNull
  java.lang.Boolean getRequireLicenseAcceptance();

  @NotNull
  java.lang.String getSummary();

  @NotNull
  java.lang.String getTags();

  @NotNull
  java.lang.String getTitle();

  @NotNull
  java.lang.Integer getVersionDownloadCount();

  @NotNull
  java.lang.String getMinClientVersion();


  String[] KeyPropertyNames = new String[] {
    "Id", 
    "Version", 
  };


}

