/*
 * Copyright 2000-2014 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/****
****
**** THIS CODE IS GENERATED BY jetbrains.buildServer.nuget.tests.server.entity.EntityGenerator$EntityBeanGenerator
**** DO NOT CHANGE!
**** Generated with class jetbrains.buildServer.nuget.tests.server.entity.EntityGenerator
**** 
*****/
package jetbrains.buildServer.nuget.server.feed.server.javaFeed.entity;

import jetbrains.buildServer.nuget.server.feed.server.index.impl.ODataDataFormat;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.joda.time.LocalDateTime;
import org.odata4j.core.OAtomEntity;

import static jetbrains.buildServer.nuget.feedReader.NuGetPackageAttributes.*;

public abstract class PackageEntityImpl  implements PackageEntityV2, OAtomEntity {

  @NotNull
  public final java.lang.String getId(){ 
    final String v = getValue(ID);
    if (v == null) { 
      return "";
    }
    return v;
  }

  @NotNull
  public final java.lang.String getVersion(){ 
    final String v = getValue(VERSION);
    if (v == null) { 
      return "";
    }
    return v;
  }

  @NotNull
  public final java.lang.String getNormalizedVersion(){
    final String v = getValue(NORMALIZED_VERSION);
    if (v == null) {
      return "";
    }
    return v;
  }

  @NotNull
  public final java.lang.String getAuthors(){ 
    final String v = getValue(AUTHORS);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.String getCopyright(){ 
    final String v = getValue(COPYRIGHT);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.String getDependencies(){ 
    final String v = getValue(DEPENDENCIES);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.String getDescription(){ 
    final String v = getValue(DESCRIPTION);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.String getIconUrl(){ 
    final String v = getValue(ICON_URL);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.Boolean getIsLatestVersion(){ 
    final String v = getValue(IS_LATEST_VERSION);
    if (v == null) { 
      return false;
    }
    return Boolean.valueOf(v);
  }


  @NotNull
  public final java.lang.Boolean getIsAbsoluteLatestVersion(){ 
    final String v = getValue(IS_ABSOLUTE_LATEST_VERSION);
    if (v == null) { 
      return false;
    }
    return Boolean.valueOf(v);
  }


  @NotNull
  public final java.lang.Boolean getIsPrerelease(){ 
    final String v = getValue(IS_PRERELEASE);
    if (v == null) { 
      return false;
    }
    return Boolean.valueOf(v);
  }


  @NotNull
  public final java.lang.String getLanguage(){ 
    final String v = getValue(LANGUAGE);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final org.joda.time.LocalDateTime getLastUpdated(){ 
    final String v = getValue(LAST_UPDATED);
    if (v != null) {
      final LocalDateTime date = ODataDataFormat.parseDate(v);
      if (date != null) return date;
    }
    return new LocalDateTime();
  }


  @NotNull
  public final java.lang.String getLicenseUrl(){ 
    final String v = getValue(LICENSE_URL);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.String getPackageHash(){ 
    final String v = getValue(PACKAGE_HASH);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.String getPackageHashAlgorithm(){ 
    final String v = getValue(PACKAGE_HASH_ALGORITHM);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.Long getPackageSize(){ 
    final String v = getValue(PACKAGE_SIZE);
    if (v == null) { 
      return 0L;
    }
    return Long.parseLong(v);
  }


  @NotNull
  public final java.lang.String getProjectUrl(){ 
    final String v = getValue(PROJECT_URL);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.String getReportAbuseUrl(){ 
    final String v = getValue(REPORT_ABUSE_URL);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.String getReleaseNotes(){ 
    final String v = getValue(RELEASE_NOTES);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.Boolean getRequireLicenseAcceptance(){ 
    final String v = getValue(REQUIRE_LICENSE_ACCEPTANCE);
    if (v == null) { 
      return false;
    }
    return Boolean.valueOf(v);
  }


  @NotNull
  public final java.lang.String getTags(){ 
    final String v = getValue(TAGS);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.String getMinClientVersion(){ 
    final String v = getValue(MIN_CLIENT_VERSION);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.String getLicenseNames(){ 
    final String v = getValue(LICENSE_NAMES);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.String getLicenseReportUrl(){ 
    final String v = getValue(LICENSE_REPORT_URL);
    if (v == null) { 
      return "";
    }
    return v;
  }


  @Nullable
  protected abstract String getValue(@NotNull final String key);


  public final java.lang.String getAtomEntityTitle() {
    return getId();
  }


  public final java.lang.String getAtomEntityAuthor() {
    return getAuthors();
  }


  public final org.joda.time.LocalDateTime getAtomEntityUpdated() {
    return getLastUpdated();
  }


  public final java.lang.String getAtomEntitySummary() {
    return getSummary();
  }

}

