/****
****
**** THIS CODE IS GENERATED BY jetbrains.buildServer.nuget.tests.server.entity.EntityGenerator$EntityInterfaceGenerator
**** DO NOT CHANGE!
*****/
package jetbrains.buildServer.nuget.server.feed.server.entity;

public interface PackageEntity  {


   java.lang.String getId();

   java.lang.String getVersion();

   java.lang.String getAuthors();

   java.lang.String getCopyright();

   org.joda.time.LocalDateTime getCreated();

   java.lang.String getDependencies();

   java.lang.String getDescription();

   java.lang.Integer getDownloadCount();

   java.lang.String getGalleryDetailsUrl();

   java.lang.String getIconUrl();

   java.lang.Boolean getIsLatestVersion();

   java.lang.Boolean getIsAbsoluteLatestVersion();

   org.joda.time.LocalDateTime getLastUpdated();

   org.joda.time.LocalDateTime getPublished();

   java.lang.String getLanguage();

   java.lang.String getLicenseUrl();

   java.lang.String getPackageHash();

   java.lang.String getPackageHashAlgorithm();

   java.lang.Long getPackageSize();

   java.lang.String getProjectUrl();

   java.lang.String getReportAbuseUrl();

   java.lang.String getReleaseNotes();

   java.lang.Boolean getRequireLicenseAcceptance();

   java.lang.String getSummary();

   java.lang.String getTags();

   java.lang.String getTitle();

   java.lang.Integer getVersionDownloadCount();


  String[] KeyPropertyNames = new String[] {
    "Id", 
    "Version", 
  };


}

