/****
****
**** THIS CODE IS GENERATED BY jetbrains.buildServer.nuget.tests.server.entity.EntityGenerator$KeyBeanGenerator
**** DO NOT CHANGE!
*****/
package jetbrains.buildServer.nuget.server.feed.server.entity;

import org.jetbrains.annotations.NotNull;

import java.util.Map;

public class PackageKey { 
  protected final Map<String, String> myFields;

  public PackageKey(@NotNull final Map<String, String> data) {
    myFields = data;
  }


  public java.lang.String getId() { 
    return java.lang.String.class.cast(myFields.get("Id"));
  }


  public java.lang.String getVersion() { 
    return java.lang.String.class.cast(myFields.get("Version"));
  }


 public boolean isValid() { 
    if (!myFields.containsKey("Id")) return false;
    if (!myFields.containsKey("Version")) return false;
    return true;
  }
}

