/****
****
**** THIS CODE IS GENERATED BY jetbrains.buildServer.nuget.tests.server.entity.EntityGenerator$EntityInterfaceGenerator
**** DO NOT CHANGE!
*****/
package jetbrains.buildServer.nuget.server.feed.server.entity;

import java.util.*;
import java.lang.*;
import org.odata4j.core.*;
import org.odata4j.internal.*;
import org.joda.time.*;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public interface PackageEntityV1  { 


  @NotNull
   java.lang.String getId();

  @NotNull
   java.lang.String getVersion();

  @Nullable
   java.lang.String getAuthors();

  @Nullable
   java.lang.String getCopyright();

  @NotNull
   org.joda.time.LocalDateTime getCreated();

  @Nullable
   java.lang.String getDependencies();

  @Nullable
   java.lang.String getDescription();

  @NotNull
   java.lang.Integer getDownloadCount();

  @Nullable
   java.lang.String getExternalPackageUrl();

  @Nullable
   java.lang.String getGalleryDetailsUrl();

  @Nullable
   java.lang.String getIconUrl();

  @NotNull
   java.lang.Boolean getIsLatestVersion();

  @NotNull
   org.joda.time.LocalDateTime getLastUpdated();

  @Nullable
   java.lang.String getLicenseUrl();

  @Nullable
   java.lang.String getPackageHash();

  @Nullable
   java.lang.String getPackageHashAlgorithm();

  @NotNull
   java.lang.Long getPackageSize();

  @Nullable
   java.lang.String getProjectUrl();

  @Nullable
   org.joda.time.LocalDateTime getPublished();

  @Nullable
   java.lang.String getReportAbuseUrl();

  @NotNull
   java.lang.Boolean getRequireLicenseAcceptance();

  @Nullable
   java.lang.String getReleaseNotes();

  @Nullable
   java.lang.String getSummary();

  @Nullable
   java.lang.String getTags();

  @Nullable
   java.lang.String getTitle();

  @NotNull
   java.lang.Integer getVersionDownloadCount();

  @NotNull
   java.lang.Integer getRatingsCount();

  @NotNull
   java.lang.Integer getVersionRatingsCount();

  @NotNull
   java.lang.Double getRating();

  @NotNull
   java.lang.Double getVersionRating();

  @Nullable
   java.lang.String getCategories();

  @Nullable
   java.lang.String getLanguage();

  @Nullable
   java.lang.String getPackageType();

  @NotNull
   java.math.BigDecimal getPrice();

  @NotNull
   java.lang.Boolean getPrerelease();


  String[] KeyPropertyNames = new String[] {
    "Id", 
    "Version", 
  };


}

