/****
****
**** THIS CODE IS GENERATED BY jetbrains.buildServer.nuget.tests.server.entity.EntityGenerator$EntityBeanGenerator
**** DO NOT CHANGE!
*****/
package jetbrains.buildServer.nuget.server.feed.server.entity;

import org.jetbrains.annotations.NotNull;

import java.util.Map;

public class PackageEntity extends PackageKey { 

  public PackageEntity(@NotNull final Map<String, String> data) {
    super(data); 
  }


  public java.lang.String getId() { 
    return java.lang.String.class.cast(myFields.get("Id"));
  }


  public java.lang.String getVersion() { 
    return java.lang.String.class.cast(myFields.get("Version"));
  }


  public java.lang.String getAuthors() { 
    return java.lang.String.class.cast(myFields.get("Authors"));
  }


  public java.lang.String getCopyright() { 
    return java.lang.String.class.cast(myFields.get("Copyright"));
  }


  public org.joda.time.LocalDateTime getCreated() { 
    return org.joda.time.LocalDateTime.class.cast(myFields.get("Created"));
  }


  public java.lang.String getDependencies() { 
    return java.lang.String.class.cast(myFields.get("Dependencies"));
  }


  public java.lang.String getDescription() { 
    return java.lang.String.class.cast(myFields.get("Description"));
  }


  public java.lang.Integer getDownloadCount() { 
    return java.lang.Integer.class.cast(myFields.get("DownloadCount"));
  }


  public java.lang.String getGalleryDetailsUrl() { 
    return java.lang.String.class.cast(myFields.get("GalleryDetailsUrl"));
  }


  public java.lang.String getIconUrl() { 
    return java.lang.String.class.cast(myFields.get("IconUrl"));
  }


  public java.lang.Boolean getIsLatestVersion() { 
    return java.lang.Boolean.class.cast(myFields.get("IsLatestVersion"));
  }


  public java.lang.Boolean getIsAbsoluteLatestVersion() { 
    return java.lang.Boolean.class.cast(myFields.get("IsAbsoluteLatestVersion"));
  }


  public org.joda.time.LocalDateTime getLastUpdated() { 
    return org.joda.time.LocalDateTime.class.cast(myFields.get("LastUpdated"));
  }


  public org.joda.time.LocalDateTime getPublished() { 
    return org.joda.time.LocalDateTime.class.cast(myFields.get("Published"));
  }


  public java.lang.String getLanguage() { 
    return java.lang.String.class.cast(myFields.get("Language"));
  }


  public java.lang.String getLicenseUrl() { 
    return java.lang.String.class.cast(myFields.get("LicenseUrl"));
  }


  public java.lang.String getPackageHash() { 
    return java.lang.String.class.cast(myFields.get("PackageHash"));
  }


  public java.lang.String getPackageHashAlgorithm() { 
    return java.lang.String.class.cast(myFields.get("PackageHashAlgorithm"));
  }


  public java.lang.Long getPackageSize() { 
    return java.lang.Long.class.cast(myFields.get("PackageSize"));
  }


  public java.lang.String getProjectUrl() { 
    return java.lang.String.class.cast(myFields.get("ProjectUrl"));
  }


  public java.lang.String getReportAbuseUrl() { 
    return java.lang.String.class.cast(myFields.get("ReportAbuseUrl"));
  }


  public java.lang.String getReleaseNotes() { 
    return java.lang.String.class.cast(myFields.get("ReleaseNotes"));
  }


  public java.lang.Boolean getRequireLicenseAcceptance() { 
    return java.lang.Boolean.class.cast(myFields.get("RequireLicenseAcceptance"));
  }


  public java.lang.String getSummary() { 
    return java.lang.String.class.cast(myFields.get("Summary"));
  }


  public java.lang.String getTags() { 
    return java.lang.String.class.cast(myFields.get("Tags"));
  }


  public java.lang.String getTitle() { 
    return java.lang.String.class.cast(myFields.get("Title"));
  }


  public java.lang.Integer getVersionDownloadCount() { 
    return java.lang.Integer.class.cast(myFields.get("VersionDownloadCount"));
  }


 public boolean isValid() { 
    if (!myFields.containsKey("Id")) return false;
    if (!myFields.containsKey("Version")) return false;
    if (!myFields.containsKey("Authors")) return false;
    if (!myFields.containsKey("Copyright")) return false;
    if (!myFields.containsKey("Created")) return false;
    if (!myFields.containsKey("Dependencies")) return false;
    if (!myFields.containsKey("Description")) return false;
    if (!myFields.containsKey("DownloadCount")) return false;
    if (!myFields.containsKey("GalleryDetailsUrl")) return false;
    if (!myFields.containsKey("IconUrl")) return false;
    if (!myFields.containsKey("IsLatestVersion")) return false;
    if (!myFields.containsKey("IsAbsoluteLatestVersion")) return false;
    if (!myFields.containsKey("LastUpdated")) return false;
    if (!myFields.containsKey("Published")) return false;
    if (!myFields.containsKey("Language")) return false;
    if (!myFields.containsKey("LicenseUrl")) return false;
    if (!myFields.containsKey("PackageHash")) return false;
    if (!myFields.containsKey("PackageHashAlgorithm")) return false;
    if (!myFields.containsKey("PackageSize")) return false;
    if (!myFields.containsKey("ProjectUrl")) return false;
    if (!myFields.containsKey("ReportAbuseUrl")) return false;
    if (!myFields.containsKey("ReleaseNotes")) return false;
    if (!myFields.containsKey("RequireLicenseAcceptance")) return false;
    if (!myFields.containsKey("Summary")) return false;
    if (!myFields.containsKey("Tags")) return false;
    if (!myFields.containsKey("Title")) return false;
    if (!myFields.containsKey("VersionDownloadCount")) return false;
    return true;
  }
}

