/****
****
**** THIS CODE IS GENERATED BY jetbrains.buildServer.nuget.tests.server.entity.EntityGenerator$EntityBeanGenerator
**** DO NOT CHANGE!
*****/
package jetbrains.buildServer.nuget.server.feed.server.entity;

import java.util.*;
import java.lang.*;
import org.odata4j.core.*;
import org.odata4j.internal.*;
import org.joda.time.*;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public abstract class PackageEntityImpl  implements PackageEntityV2, OAtomEntity { 
  protected final Map<String, String> myFields;

  public PackageEntityImpl(@NotNull final Map<String, String> data) {
    myFields = data;
  }



  @NotNull
  public final java.lang.String getId(){ 
    final String v = myFields.get("Id");
    if (v == null) { 
      return "";
    }
    return v;
  }


  @NotNull
  public final java.lang.String getVersion(){ 
    final String v = myFields.get("Version");
    if (v == null) { 
      return "";
    }
    return v;
  }


  @Nullable
  public final java.lang.String getAuthors(){ 
    final String v = myFields.get("Authors");
    return v;
  }


  @Nullable
  public final java.lang.String getCopyright(){ 
    final String v = myFields.get("Copyright");
    return v;
  }


  @Nullable
  public final java.lang.String getDependencies(){ 
    final String v = myFields.get("Dependencies");
    return v;
  }


  @Nullable
  public final java.lang.String getDescription(){ 
    final String v = myFields.get("Description");
    return v;
  }


  @Nullable
  public final java.lang.String getIconUrl(){ 
    final String v = myFields.get("IconUrl");
    return v;
  }


  @NotNull
  public final java.lang.Boolean getIsLatestVersion(){ 
    final String v = myFields.get("IsLatestVersion");
    if (v == null) { 
      return false;
    }
    return Boolean.valueOf(v);
  }


  @NotNull
  public final java.lang.Boolean getIsAbsoluteLatestVersion(){ 
    final String v = myFields.get("IsAbsoluteLatestVersion");
    if (v == null) { 
      return false;
    }
    return Boolean.valueOf(v);
  }


  @NotNull
  public final org.joda.time.LocalDateTime getLastUpdated(){ 
    final String v = myFields.get("LastUpdated");
    if (v == null) { 
      return new org.joda.time.LocalDateTime();
    }
    return jetbrains.buildServer.nuget.server.feed.server.index.ODataDataFormat.parseDate(v);
  }


  @Nullable
  public final java.lang.String getLanguage(){ 
    final String v = myFields.get("Language");
    return v;
  }


  @Nullable
  public final java.lang.String getLicenseUrl(){ 
    final String v = myFields.get("LicenseUrl");
    return v;
  }


  @Nullable
  public final java.lang.String getPackageHash(){ 
    final String v = myFields.get("PackageHash");
    return v;
  }


  @Nullable
  public final java.lang.String getPackageHashAlgorithm(){ 
    final String v = myFields.get("PackageHashAlgorithm");
    return v;
  }


  @NotNull
  public final java.lang.Long getPackageSize(){ 
    final String v = myFields.get("PackageSize");
    if (v == null) { 
      return 0L;
    }
    return Long.parseLong(v);
  }


  @Nullable
  public final java.lang.String getProjectUrl(){ 
    final String v = myFields.get("ProjectUrl");
    return v;
  }


  @Nullable
  public final java.lang.String getReportAbuseUrl(){ 
    final String v = myFields.get("ReportAbuseUrl");
    return v;
  }


  @Nullable
  public final java.lang.String getReleaseNotes(){ 
    final String v = myFields.get("ReleaseNotes");
    return v;
  }


  @NotNull
  public final java.lang.Boolean getRequireLicenseAcceptance(){ 
    final String v = myFields.get("RequireLicenseAcceptance");
    if (v == null) { 
      return false;
    }
    return Boolean.valueOf(v);
  }


  @Nullable
  public final java.lang.String getTags(){ 
    final String v = myFields.get("Tags");
    return v;
  }



  public final java.lang.String getAtomEntityTitle() {
    return getId();
  }


  public final java.lang.String getAtomEntityAuthor() {
    return getAuthors();
  }


  public final org.joda.time.LocalDateTime getAtomEntityUpdated() {
    return getLastUpdated();
  }


  public final java.lang.String getAtomEntitySummary() {
    return getSummary();
  }

}

